version = 1

[instruments.function_generator]
connection = { protocol = "gpib", board = 0, address = 11 }
model = "WF1946B"

[instruments.oscilloscope]
connection = { protocol = "tcpip", ip = "10.249.11.19", port = 55255 }
model = "DHO5108"
memory_depth = 10_000_000

[timebase]
t0 = -0.5e-3 # seconds
dt = 500e-12 # seconds

[roles]
sensor_ch = [1, 4]
reference_ch = [3] # Supports only one reference channel
signal_ch = [2]

# Channel for current sensor
[[channels]]
index = 1
factor = -39364.84663082185
label = "$B$"
unit_out = "T"

# Channel for signal
[[channels]]
index = 2

[[channels]]
index = 3

[[channels]]
index = 4
factor = 1
label = "$V$"
unit_out = "V"


[pulse]
bg_window_before = { start = -5e-3, end = -0.1e-3 }
bg_window_after = { start = 4.2e-3, end = 15e-3 }

[lockin]
workers = 4
filter_length_samples = 20
stride_samples = 2000

[phase]
use_signal_ch = [2]

[kerr]
use_sensor_ch = 1 # Supports only one sensor channel
kerr_type = "standard" # "standard" or "harmonics"
factor = 1 
