version = 1

[instruments.function_generator]
connection = { protocol = "gpib", board = 0, address = 11 }
model = "WF1946B"

[instruments.oscilloscope]
connection = { protocol = "tcpip", ip = "10.249.11.19", port = 55255 }
model = "DHO5108"
memory_depth = 10_000_000

[timebase]
t0 = -1.5e-3 # seconds
dt = 500e-12 # seconds

[roles]
sensor_ch = [1]
reference_ch = [3] # Supports only one reference channel
signal_ch = [2]

# Channel for current sensor
[[channels]]
index = 1
factor = -4.875405593e6
label = "$I$"
unit_out = "A"

# Channel for signal
[[channels]]
index = 2

[[channels]]
index = 3

# [[channels]]
# index = 4
# factor = 1
# label = "$V$"
# unit_out = "V"
#
# [[channels]]
# index = 5
# factor = 1
# label = "$F$"
# unit_out = "f"


[pulse]
bg_window_before = { start = -5e-3, end = -0.5e-3 }
bg_window_after = { start = 2.5e-3, end = 15e-3 }

[lockin]
workers = 4
filter_length_samples = 20
stride_samples = 2000

